
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = yes
WPM_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# Optimization
TAP_DANCE_ENABLE = no
STENO_ENABLE = no
TERMINAL_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
KEY_LOCK_ENABLE = no
VELOCIKEY_ENABLE = no

EXTRAFLAGS += -flto
